development:
  adapter: postgresql
  database: project-one-development

test:
  adapter: postgresql
  database: project-one-test
  
production:
  adapter: postgresql
  database: project-one-production

